collection:
  custom_name:
    http_method: GET
    path: /api/lol/kek
    body: |
      {
        "test": 123,
        "name": "yoda",
        "prices": [123.123,321.321]
      }
    body_path: ./json/test.json
    status: 200
    collect_params:
      query_param: "test_query"
      json_path: "collect_key"

  custom_name2:
    http_method: GET
    path: /api/foo/bar
    body_path: ./json/test.json
    status: 200
    collect_params:
      json_path: "collect_key"

  post_custom_name2:
    http_method: POST
    path: /api/foo/put
    body: |
      {
        "test": 123,
        "name": "yoda",
        "prices": [123.123,321.321]
      }
    body_path: ./json/test.json
    status: 201

  without_collect_settings:
    http_method: GET
    path: /api/w
    body: |
      {
        "test": 123,
        "name": "yoda",
        "prices": [123.123,321.321]
      }
    body_path: ./json/test.json
    status: 201
    collect_params:
      json_path: "collect_key"
      query_param: "test_query"
