collection:
  custom_name:
    http_method: GET
    path: /api/lol/kek
    body: |
      {
        "test": 123,
        "name": "yoda",
        "prices": [123.123,321.321]
      }
    body_path: ./json/test.json
    status: 200

  custom_name2:
    http_method: GET
    path: /api/foo/bar
    body_path: ./json/test.json
    status: 200

  post_custom_name2:
    http_method: POST
    path: /api/foo/put
    body: |
      {
        "test": 123,
        "name": "yoda",
        "prices": [123.123,321.321]
      }
    body_path: ./json/test.json
    status: 201
